### ISSUE TITLE
TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by Bhanuka94** [idleberg/generator-nsis#3]
Windows 10
NodeJS Version: v8.16.0 and v12.16.1
Electron: 2.0.18

All the commands were followed in accordance with the documentation([https://github.com/idleberg/generator-nsis#readme])

But after running "**yo nsis**", the following error pops up.

```
TypeError: Cannot read property 'toString' of null
    at stringify (C:\Users\omak\AppData\Roaming\nvm\v8.16.0\node_modules\generator-nsis\node_modules\makensis\dist\util.js:92:17)
    at Object.spawnMakensisSync (C:\Users\omak\AppData\Roaming\nvm\v8.16.0\node_modules\generator-nsis\node_modules\makensis\dist\util.js:292:20)    
    at hdrInfoSync (C:\Users\omak\AppData\Roaming\nvm\v8.16.0\node_modules\generator-nsis\node_modules\makensis\dist\makensis.js:73:19)
    at nsisDirSync (C:\Users\omak\AppData\Roaming\nvm\v8.16.0\node_modules\generator-nsis\node_modules\makensis\dist\makensis.js:211:19)
    at getAllLibraries (C:\Users\omak\AppData\Roaming\nvm\v8.16.0\node_modules\generator-nsis\generators\app\index.js:179:20)
    at module.exports.inquirer (C:\Users\omak\AppData\Roaming\nvm\v8.16.0\node_modules\generator-nsis\generators\app\index.js:445:57)
    at Object.<anonymous> (C:\Users\omak\AppData\Roaming\nvm\v8.16.0\node_modules\generator-nsis\node_modules\yeoman-generator\lib\index.js:976:25)  
    at C:\Users\omak\AppData\Roaming\nvm\v8.16.0\node_modules\generator-nsis\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Users\omak\AppData\Roaming\nvm\v8.16.0\node_modules\generator-nsis\node_modules\run-async\index.js:26:19
```
![asasa](https://user-images.githubusercontent.com/51482638/87390625-dec6fa00-c5c6-11ea-978d-57e4258f8f3a.PNG)

How to resolve this issue...?

**Comment by idleberg** [comment]
This error pops up immediately after running the command (without any further input?). Can you please specify the version of the generator and its `makensis` dependency?

**Comment by Bhanuka94** [comment]
Version of the generator: **0.8.4**

I think the reason for this error is because I use the electron-builder to create an NSIS installer at the same time. Maybe conflicts occur.
